### ISSUE TITLE
Profile Feluda for its throughput and memory usage

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/services-infrastructure#6]
1. Figure out how many concurrent requests Feluda can handle
2. Identify bottleneck processes or function calls to be optimized later
3. Figure out the relationship between memory usage and number of requests

**Comment by dennyabrain** [comment]
Found some tools that might be useful
- https://httpd.apache.org/docs/2.4/programs/ab.html
- http://supervisord.org/introduction.html

**Comment by d80ep08th** [comment]
# Installing Feluda
When someone goes over to https://github.com/tattle-made/tattle-api and clones the repo and tries to start feluda using 
`docker-compose up` it's difficult to start it easily . The way to get Feluda actually up and running is unconventional, something I figured out by collaborating with @dennyabrain .

This is how to get Feluda actually up and running to get started with playing it:
#### Clone the tattle api repo
```
$ git clone https://github.com/tattle-made/tattle-api.git
$ cd tattle-api
```
#### Replace the contents of docker-compose.yml in the repository with the following :
```
version: "3.5"

services:
  store:
    container_name: systemd_es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    volumes:
      - ./.docker/es/data:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  queue:
    image: rabbitmq:3.8.7-management
    container_name: systemd_rabbitmq
    hostname: rabbit
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret-cookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Admin123"
    ports:
      - 5672:5672
      - 15672:15672

  api:
    container_name: systemd_feluda_api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: debug
    volumes:
      - ./src/api:/app
    env_file: ./src/api/development.env
    ports:
      - 7000:7000
      - 5678:5678
    command: tail -f /dev/null
    #depends_on:
    #  store:
    #    condition: service_started
    #  queue:
    #    condition: service_started

```
It is almost similar to the file in https://github.com/tattle-made/kosh-v2/discussions/8#discussioncomment-1811845

#### In the repository, in `/src/api` directory, add the file `development.env` with the following content : 
```
MQ_USERNAME=admin  
MQ_PASSWORD=Admin123
MQ_HOST=rabbitmq
AWS_ACCESS_KEY_ID=XXX  
AWS_SECRET_ACCESS_KEY=XXXX
AWS_SECRET_ACCESS_KEY_ID=XXXX
AWS_BUCKET=config.tattle.co.in  
S3_CREDENTIALS_PATH=google-api/tattle-api-google.json
GOOGLE_APPLICATION_CREDENTIALS="credentials.json"  
ES_USERNAME=XXXXX  
ES_PASSWORD=XXXXX  
ES_HOST=es  
KOSH_API=http://kosh_api:8000/
```

#### chown
```
$ sudo chown -R 1000:1000 tattle-api/.docker/es/data
```

#### Bring up the containers
```
$ docker-compose up
```
# What's Left?

1. No actual stats have been figured out.
2. There is still no script to attack feluda
3. The tools needed to play and work with this task have not yet been selected.
